
import java.awt.Color;
import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 897034
 */
public class AcidBasePage extends javax.swing.JFrame {
		private int acidSelect=0;
		private int baseSelect=0;
		private int counter=0;
		private double acidConcentration;
		private double baseConcentration;
		private int labelAcid=0;
		private int labelBase=0;
		
	/**
	 * Creates new form simulation
	 */
	public AcidBasePage() {
		initComponents();
		baseVisible(false);
		acidVisible(false);
		buttonStart.setVisible(false);
		textInstruction.setLineWrap(true);
		setLocationRelativeTo(null);
	}	
	public void acidVisible(boolean visible){
		if (visible){
			buttonHcl.setVisible(true);
			buttonHcl.setEnabled(true);
			buttonHcn.setVisible(true);
			buttonHcn.setEnabled(true);
			buttonHf.setVisible(true);
			buttonHf.setEnabled(true);
			
		}
		else {
			buttonHcl.setVisible(false);
			buttonHcl.setEnabled(false);
			buttonHcn.setVisible(false);
			buttonHcn.setEnabled(false);
			buttonHf.setVisible(false);
			buttonHf.setEnabled(false);
		}
	}
	
	public void hideAll() {
			buttonHcl.setVisible(false);
			buttonHcn.setVisible(false);
			buttonHf.setVisible(false);
			buttonNaoh.setVisible(false);
			buttonNh3.setVisible(false);
			buttonCo3.setVisible(false);
			buttonStart.setVisible(true);
	}
			
	public void baseVisible(boolean visible){
		if (visible){
			buttonNaoh.setVisible(true);
			buttonNaoh.setEnabled(true);
			buttonNh3.setVisible(true);
			buttonNh3.setEnabled(true);
			buttonCo3.setVisible(true);
			buttonCo3.setEnabled(true);
		}
		else{
			buttonNaoh.setVisible(false);
			buttonNaoh.setEnabled(false);
			buttonNh3.setVisible(false);
			buttonNh3.setEnabled(false);
			buttonCo3.setVisible(false);
			buttonCo3.setEnabled(false);
		}
	}
	
	public void getAcidConcentration(){
		acidConcentration=UserInput.getDouble("Concentration");
		while (acidConcentration<1 || acidConcentration>5){
			acidConcentration=UserInput.getDouble("Please enter concentration between 1 and 5");
		}
		System.out.println("Acid Concentration: "+acidConcentration + "M");
	}
	
	public void getBaseConcentration(){
		baseConcentration=UserInput.getDouble("Concentration");
		while (baseConcentration<1 || baseConcentration>5){
			baseConcentration=UserInput.getDouble("Please enter concentration between 1 and 5");
		}
		System.out.println("Base Concentration: "+baseConcentration+"M");
	}
	
	
	
	

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAcid = new javax.swing.JButton();
        buttonBase = new javax.swing.JButton();
        buttonHcl = new javax.swing.JButton();
        buttonHcn = new javax.swing.JButton();
        buttonHf = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textInstruction = new javax.swing.JTextArea();
        buttonNaoh = new javax.swing.JButton();
        buttonNh3 = new javax.swing.JButton();
        buttonCo3 = new javax.swing.JButton();
        panelDraw = new javax.swing.JPanel();
        buttonStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonAcid.setText("Acid");
        buttonAcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcidActionPerformed(evt);
            }
        });

        buttonBase.setText("Base");
        buttonBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaseActionPerformed(evt);
            }
        });

        buttonHcl.setText("HCl");
        buttonHcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHclActionPerformed(evt);
            }
        });

        buttonHcn.setText("HCN");
        buttonHcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHcnActionPerformed(evt);
            }
        });

        buttonHf.setText("HF");
        buttonHf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHfActionPerformed(evt);
            }
        });

        textInstruction.setEditable(false);
        textInstruction.setColumns(20);
        textInstruction.setRows(5);
        textInstruction.setText("Select Acid or Base.\nMaximum concentration\nof the reagents is 5M\n");
        jScrollPane2.setViewportView(textInstruction);

        buttonNaoh.setText("NaOH");
        buttonNaoh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNaohActionPerformed(evt);
            }
        });

        buttonNh3.setText("NH₃");
        buttonNh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNh3ActionPerformed(evt);
            }
        });

        buttonCo3.setText("CO₃²⁻");
        buttonCo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCo3ActionPerformed(evt);
            }
        });

        buttonStart.setText("Start Titration!");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDrawLayout = new javax.swing.GroupLayout(panelDraw);
        panelDraw.setLayout(panelDrawLayout);
        panelDrawLayout.setHorizontalGroup(
            panelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDrawLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panelDrawLayout.setVerticalGroup(
            panelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDrawLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(buttonStart)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonBase, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAcid, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(panelDraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonNh3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonHf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonHcn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonHcl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNaoh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttonCo3))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonHcl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonHcn)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHf))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(buttonAcid))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonNaoh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonNh3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(buttonBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonCo3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcidActionPerformed

		if (counter==0){
			acidVisible(true);
			buttonAcid.setEnabled(false);
			buttonBase.setEnabled(false);
		}
		else if (counter==1){
			acidVisible(true);
			baseVisible(false);
			buttonAcid.setEnabled(false);
			buttonBase.setEnabled(false);
			
		}
		else {
			buttonAcid.setEnabled(false);
			buttonBase.setEnabled(false);
		}
		
	
		
    }//GEN-LAST:event_buttonAcidActionPerformed

    private void buttonBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaseActionPerformed
        // TODO add your handling code here:
		if (counter==0){
			baseVisible(true);
			buttonAcid.setEnabled(false);
			buttonBase.setEnabled(false);
		}
		else if (counter==1){
			baseVisible(true);
			acidVisible(false);
			buttonBase.setEnabled(false);
		}
		else {
			buttonAcid.setEnabled(false);
			buttonBase.setEnabled(false);
		}
		
		
		
    }//GEN-LAST:event_buttonBaseActionPerformed

    private void buttonHclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHclActionPerformed
        // TODO add your handling code here:getAcidConcentration();
		counter++;
		System.out.println("Acid: HCl");
		getAcidConcentration();
		if (counter==1){
			buttonBase.setEnabled(true);
		}
		else if (counter==2) {
			buttonBase.setEnabled(false);
			buttonAcid.setEnabled(false);
			hideAll();
		}
		acidVisible(false);
		
		labelAcid=1;
    }//GEN-LAST:event_buttonHclActionPerformed
	
    private void buttonHcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHcnActionPerformed
        // TODO add your handling code here:
		System.out.println("Acid: HCN");
		getAcidConcentration();
		counter++;
		if (counter==1){
			buttonBase.setEnabled(true);
		}
		else if (counter==2) {
			buttonBase.setEnabled(false);
			buttonAcid.setEnabled(false);
			hideAll();
		}
		acidVisible(false);
		labelAcid=2;
	
    }//GEN-LAST:event_buttonHcnActionPerformed

    private void buttonHfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHfActionPerformed
		counter++;
		System.out.println("Acid: HF");
		getAcidConcentration();
		if (counter==1){
			buttonBase.setEnabled(true);
		}
		else if (counter==2){
			buttonBase.setEnabled(false);
			buttonAcid.setEnabled(false);
			hideAll();
		}
		acidVisible(false);
		
		labelAcid=3;
    }//GEN-LAST:event_buttonHfActionPerformed

    private void buttonNaohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNaohActionPerformed
		counter++;
		System.out.println("Base: NaOH");
		getBaseConcentration();
		if (counter==1){
			buttonAcid.setEnabled(true);
		}
		else if (counter==2){
			buttonAcid.setEnabled(false);
			buttonBase.setEnabled(false);
			hideAll();
		}
		baseVisible(false);
		
		labelBase=1;
		
    }//GEN-LAST:event_buttonNaohActionPerformed

    private void buttonNh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNh3ActionPerformed
		counter++;
		System.out.println("Base: NH3");
		getBaseConcentration();
		if (counter==1){
			buttonAcid.setEnabled(true);
		}
		else if (counter==2){
			buttonAcid.setEnabled(false);
			buttonBase.setEnabled(false);
			hideAll();
		}
		baseVisible(false);
		labelBase=2;
			
    }//GEN-LAST:event_buttonNh3ActionPerformed

    private void buttonCo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCo3ActionPerformed
		counter++;
		System.out.println("Base: Co3 2-");
		getBaseConcentration();
		if (counter==1){
			buttonAcid.setEnabled(true);
		}
		else if (counter==2){
			buttonAcid.setEnabled(false);
			buttonBase.setEnabled(false);
			hideAll();
		}
		baseVisible(false);
		
		labelBase=3;
		
		
		/*Color c = new Color(255,16,0);
		Graphics g = panelDraw.getGraphics();
		g.setColor(c);
		g.fillRect(0,0,panelDraw.getWidth(), panelDraw.getHeight());
		*/
    }//GEN-LAST:event_buttonCo3ActionPerformed

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        TitrationInfo info = new TitrationInfo(acidConcentration, baseConcentration,labelAcid,labelBase);
		Simulation s = new Simulation(info);
		s.setVisible(true); 
		dispose();
    }//GEN-LAST:event_buttonStartActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AcidBasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AcidBasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AcidBasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AcidBasePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AcidBasePage().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcid;
    private javax.swing.JButton buttonBase;
    private javax.swing.JButton buttonCo3;
    private javax.swing.JButton buttonHcl;
    private javax.swing.JButton buttonHcn;
    private javax.swing.JButton buttonHf;
    private javax.swing.JButton buttonNaoh;
    private javax.swing.JButton buttonNh3;
    private javax.swing.JButton buttonStart;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDraw;
    private javax.swing.JTextArea textInstruction;
    // End of variables declaration//GEN-END:variables
}
